### ISSUE TITLE
Recurse directories

### ISSUE THREAD

**Issue by tormento** [pcroland/deew#13]
In the case of seasonal episodes, it would be nice to have an option to recurse directories to encode every audio file inside them.

**Comment by pcroland** [comment]
Use a shell that supports wildcard

**Comment by tormento** [comment]
@pcroland yes but it wouldn't go multithread

**Comment by pcroland** [comment]
It would

**Comment by tormento** [comment]
@pcroland I have just tried: 

for /R %%a in (*51*.dts) do D:\Eseguibili\Sonoro\DEEW\deew.py -i "%%a" -b 640

gets one file only

**Comment by pcroland** [comment]
You need to specify all files/forders after `-i`. With the for loop you start deew multiple times.
