### ISSUE TITLE
Custom default bitrates

### ISSUE THREAD

**Issue by tormento** [pcroland/deew#14]
It would be nice to have a place in configuration file  where to store the default bitrates for the number of audio channels, such as:

7.1: 640 kbps
5.1: 320 kbps
2.0: 128 kbps

and so.

**Comment by pcroland** [comment]
It's not that useful but maybe I'll add it later when I have to touch the config's behaviour.

**Comment by pcroland** [comment]
added configurable default bitrates in 2.2.0
