### ISSUE TITLE
Progress bar not working as intended

### ISSUE THREAD

**Issue by tormento** [pcroland/deew#17]
As you can see, I am testing deew a lot.

I have found that with very complex files. the progress bar doesn't work as intended, as it jumps from zero to 100% and doesn "scroll" at all.

My environment is pure Windows 11 (no WSL), with Command prompt under Terminal Preview.

deew python only version

[Test file](https://pixeldrain.com/u/9p3GYV2k)

**Comment by pcroland** [comment]
If the input file's length can't be parsed, the progress bar will show a spinning animation for the intermediate phase (ffmpeg)
