### ISSUE TITLE
DDP Encoder mode bluray

### ISSUE THREAD

**Issue by boulderdash09** [pcroland/deew#24]
Hello,

In the code we can read this line :

```
 if bitrate > 1024:
                    xml_base['job_config']['filter']['audio']['pcm_to_ddp']['encoder_mode'] = 'bluray'
```

However, according to the documentation, bluray encoder_mode should be available for ddp 7.1 >= 768kbps

I think the behavior in the code should be modified (or at least the encoder_mode could be specified in the arguments)

Thank you !

**Comment by pcroland** [comment]
The standard mode is more efficient so there's no point of encoding 7.1 768/1024kbps with bluray mode.

**Comment by boulderdash09** [comment]
more efficient but less compatible :)

**Comment by pcroland** [comment]
I'll add an option for it.

**Comment by pcroland** [comment]
added `-fs`/`--force-standard` and `-fb`/`--force-bluray` options in 2.2.0

**Comment by boulderdash09** [comment]
Thank you !

Just one thing, you forgot to add the force-bluray args in this part to produce eb3 files :

```
if aformat == 'ddp':
            if bitrate > 1024:
                xml['job_config']['output']['ec3']['file_name'] = f'\"{basename(filelist[i], "eb3")}\"'
            else:
                xml['job_config']['output']['ec3']['file_name'] = f'\"{basename(filelist[i], "ec3")}\"'
```

**Comment by pcroland** [comment]
fixed, thanks.

**Comment by boulderdash09** [comment]
In fact you did an inversion between args standard and bluray in the code :) -fb still produces ec3 files

**Comment by pcroland** [comment]
Oh, thanks. I looked at the other part where args are being used and applied the same alternating value setup but at the file extension part i used an if else lol.
