### ISSUE TITLE
Ability to spoof datetime to bypass expired license.

### ISSUE THREAD

**Issue by george-avn** [pcroland/deew#27]
This should not interfere with the system clock, and should be hooked onto the dee.exe process

**Comment by pcroland** [comment]
Sorry, I can't do that, don't want this package taken down. I've sent you an e-mail if `abtzi*******os@gmail.com` is still your address.

**Comment by george-avn** [comment]
> Sorry, I can't do that, don't want this package taken down. I've sent you an e-mail if `abtzi*******os@gmail.com` is still your address.

Understandable, thank you.
