### ISSUE TITLE
deew can't start because "api-ms-win-core-path-l1-1-0.dll is missing from your computer".

### ISSUE THREAD

**Issue by filler56789** [pcroland/deew#34]
**Description of the the bug**
I'm using 64-bit Windows 7 and the message above appears when I call deew on the command-line.
After I click the OK button, then there appears a new error message:
«Error loading Python DLL 'C:\TEMP-D~1\New-TMP\_MEI21602\python310.dll'.
LoadLibrary: The specified module could not be found.»
_Which is weird, because the README.md says_:
**``Python (you don't need it if you use a standalone build of deew)´´**.
_FWIW: _MEI21602 is a directory created and used by yt-dlp.exe_ :–/

**Version**
Latest.

**OS**
64-bit Windows 7.

**Comment by pcroland** [comment]
the standalone version won't work on Windows 7, update your Windows.

**Comment by filler56789** [comment]
Question: the problem is with deew.exe itself, or with the version of Python with which it was ``compiled´´?
Anyway, updating my Windows is not an option, unless you give me a brand-new computer :-)

**Comment by pcroland** [comment]
pyinstaller and Python >3.8 doesn't support Windows 7. Try to install Python 3.8 and install deew with pip.

**Comment by filler56789** [comment]
OK, then please and at least update your README.md.
Windows 7 is the new Windows XP and it won't die as fast as Microsoft and the Python devilopers would like :-)

**Comment by pcroland** [comment]
Windows 7 has reached its EOL in 2020, what should I change in the README?

**Comment by filler56789** [comment]
You should add that your builds of **deew.exe** are compiled with a version of Python that requires Windows 10 or higher.
As I said, not everybody will stop using Windows 7 only because Microsoft wants or because the creators and maintainers of Python, Qt and etc. are narrow-minded.

**Comment by pcroland** [comment]
It's not because they are narrow-minded. They don't intentionally make tools/programs not work on Windows 7, they would have to spend extra time for supporting old OSs. Every OS has an EOL date for a reason.

**Comment by shirt-dev** [comment]
> Question: the problem is with deew.exe itself, or with the version of Python with which it was ``compiled´´? Anyway, updating my Windows is not an option, unless you give me a brand-new computer :-)

https://www.microsoft.com/en-us/software-download/windows10

**Comment by filler56789** [comment]
_>> pcroland wrote:_
«It's not because they are narrow-minded.»

Well, SH¡T-dev's useless comment proved that you are wrong. :-)

**Comment by filler56789** [comment]
> > Question: the problem is with deew.exe itself, or with the version of Python with which it was ``compiled´´? Anyway, updating my Windows is not an option, unless you give me a brand-new computer :-)
> 
> https://www.microsoft.com/en-us/software-download/windows10

Not all personal computers are able to run Windows 10 smoothly (or at all).
Evidently you are rich (or well-off at least) and assumes that I am too.
But thanks for your useless and trollish comment anyway.

**Comment by pcroland** [comment]
Asking for Windows 7 support is like asking to port it to basic, because

**Comment by pcroland** [comment]
Asking for Windows 7 support is like asking for a basic port because you have a Commodore or something like that. I doubt that a PC couldn't run Windows 10 if it can handle Windows 7 especially with some tweaks if needed.

**Comment by shirt-dev** [comment]
> > > Question: the problem is with deew.exe itself, or with the version of Python with which it was ``compiled´´? Anyway, updating my Windows is not an option, unless you give me a brand-new computer :-)
> > 
> > 
> > https://www.microsoft.com/en-us/software-download/windows10
> 
> Not all personal computers are able to run Windows 10 smoothly (or at all). Evidently you are rich (or well-off at least) and assumes that I am too. But thanks for your useless and trollish comment anyway.

https://www.howtogeek.com/450864/will-windows-10-work-on-my-computer/
![image](https://user-images.githubusercontent.com/2660574/188023265-582f9feb-46cd-4676-bd90-ae6517d34cc9.png)

**Comment by ted423** [comment]
Even computers from 10 years ago can install win10.

**Comment by ValZapod** [comment]
> personal computers are able to run Windows 10 smoothly (or at all).

But those computers will not be able to run DEE. dee.exe is compiled in visual studio with AVX2 support, so even worse than some other stuff like games that **only** require SSE4.2.

**Comment by tormento** [comment]
I am currently using (and abusing) a i7-2600k, with no AVX2 support (unfortunately) and everything works fine on Windows 11.

**Comment by ValZapod** [comment]
So Dolby Media encoder works for you fine?

**Comment by pcroland** [comment]
I guess he uses DEE with deew.

**Comment by tormento** [comment]
@ValZapod I have tried to load DME and it opens but never tried to encode. Usually, as @pcroland said, I use DEE.

I can just imagine that they share the same engine, anyway.

**Comment by ValZapod** [comment]
UI may not work. But okay. I was wrong then, those people were mistaken.

**Comment by alexdns1** [comment]
@pcroland dont want to resurrect an old issue but

Windows 7 - Windows 7 Extended Security Updates 2022: January 12, 2022 - January 10, 2023
https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq

Windows 2012 based on 7 has the exact same issue server goes to 2025
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2
