### ISSUE TITLE
[IMPROVEMENT] Show input's bitrate if it can be fetched and only one input is given

### ISSUE THREAD

**Issue by tormento** [pcroland/deew#36]
Given a proper input format. it would be of some use to have the input bitrate exposed too in the deew banner.

**Comment by pcroland** [comment]
Not possible due to multiple inputs being supported and you can't get every input's bitrate in the first place.

**Comment by tormento** [comment]
@pcroland As I wrote, given proper input :)

**Comment by pcroland** [comment]
@tormento reopened it
