### ISSUE TITLE
[BUG] Add proper error message for mono TrueHD encoding

### ISSUE THREAD

**Issue by pcroland** [pcroland/deew#41]
**Description of the the bug**
deew tries to encode mono TrueHD

**Version**
Latest

**OS**
Every

**Comment by ValZapod** [comment]
And 44.1k too. Even though ffmpeg can encode that, no problem.

ffmpeg -h encoder=truehd

    General capabilities: delay small exp
    Threading capabilities: none
    Supported sample rates: 44100 48000 88200 96000 176400 192000
    Supported sample formats: s16 s32
    Supported channel layouts: stereo 5.0 5.1

**Comment by ValZapod** [comment]
BTW, 44.1 is supported by HW bitstream players like LG C9 internal speackers, no problem.

**Comment by pcroland** [comment]
from the readme:
- automatic sample rate conversion using ffmpeg's soxr resampler in case of an unsupported sample rate
  - for DD/DDP unsupported rates will be converted to 48 kHz
  - for TrueHD unsupported rates will be converted to 48 kHz if source sample rate is lower than 72 kHz, otherwise will be converted to 96 kHz

DEE doesn't support anything else other than 48kHz for DD and DDP and only 48 and 96kHz for TrueHD

**Comment by ValZapod** [comment]
Dolby Reference player supports playing mono with this script, just change truehddec-presentation=2 or 6 or 8 instead of 16 

https://gist.github.com/Plazik/e950267cc580bcde371ea7879aaa3d5d
