### ISSUE TITLE
[BUG] Compatibility issue with recent FFmpeg nightly builds with 8ch audio

### ISSUE THREAD

**Issue by l00tzOMG** [pcroland/deew#46]
**Description of the the bug**
Recent versions of nightly FFmpeg refuse to create 8ch wav files. Creating w64 files and adjusting the xml file accordingly seems to solve the problem.

**Proposition**
Change wav extension to w64 in deew. (at least for 8ch audios)

**Comment by pcroland** [comment]
fixed in 2.9.5
