### ISSUE TITLE
[IMPROVEMENT] Disabling dynamic compression

### ISSUE THREAD

**Issue by Qarmaa** [pcroland/deew#50]
Using 2.9.5 and have and issue here. So I was trying to encode a 5.1 audio with in DD with 448 kbps, forced -31 dn and getting the dynamics compression for some reason (on top of lowering whole file volume even with -31 dn). Same results with -27 DN value. Am I missing something? Haven't have something like that with neither Dolby Media Production Suite or just ffmpeg.

![image_2023-03-23_03-38-31](https://user-images.githubusercontent.com/22600833/227070953-6fa10b04-3c8a-4e1a-8afa-6827d2bb45c6.png)
![image_2023-03-23_03-38-31 (2)](https://user-images.githubusercontent.com/22600833/227070973-6ab71b7e-2b9b-4e8f-a6cc-a1419cd24615.png)

**Comment by pcroland** [comment]
@Qarmaa you should provide sample files

**Comment by Mahaaveer** [comment]
I feel the same about the DRC. Has anyone figured a way to keep DEE from messing up the volume levels ? One time i noticed DEE dialing down fine details such as wind and breaking glass etc.., ruining the experience. i had to input manual dialnorm to up the volume. On the other hand, it lifted up ambient noises. I just don't want the DEE to touch the volume.

**Comment by ValZapod** [comment]
Dolby reference player can disable DRC as follows and that will also produce no encoder delay (gapless at the start at least) and 32 bit integer file: "C:\Program Files\Dolby\Dolby Reference Player\gst-launch-1.0.exe" --gst-plugin-path "C:\Program Files\Dolby\Dolby Reference Player/gst-plugins" filesrc location=C:\\tmp\\atmos\\gapless.eac3 ! dlbac3parse ! dlbaudiodecbin ac3dec-drop-delay=true **ac3dec-drc-suppress=true** out-ch-config=13 ! audio/x-raw,**format=S32LE** ! wavenc ! filesink location=Z:\zE.L111.wav

**Comment by Mahaaveer** [comment]
> 
This Generates wav file from eac3 disabling the drc ? 
Can it be used to encode eac3 without the drc ?

Thanks!

**Comment by pcroland** [comment]
no

**Comment by ValZapod** [comment]
>Can it be used to encode eac3 without the drc

FFmpeg EAC3 encoder does not do DRC, e.g.
