### ISSUE TITLE
[REQUEST]  Allow DTS 3/1 encoding to dolby formats

### ISSUE THREAD

**Issue by nautilus7** [pcroland/deew#55]
Hi, there is a 3/1 DTS channel configuration, which is 3 front channels (right, center, left) and 1 surround channel. This format cannot be encoded to any of the Dolby formats, as they require either 2, 4, 6, or 8 channels.

What about automatically doubling the surround channel (multiply by sqrt(2) each surround to maintain the same sound level) and adding a dummy (empty) LFE channel to create a compatible 5.1 input layout?

What that be possible?

**Comment by pcroland** [comment]
deew does not handle automatic channel layout conversions for weird layouts, you need to manually fix it before encoding
