### ISSUE TITLE
[BUG] All encoding fails after upgrading from 3.0.1 to 3.2.1

### ISSUE THREAD

**Issue by GrzeWier** [pcroland/deew#59]
**Description of the the bug**
Hi
I recently upgraded from DEEW 3.0.1 to 3.2.1
Now all TrueHD to DDP encoding fails with this error:
pcm_to_ddp: Check input and downmix config. Resulting output channels: 0 is not allowed. Valid value(s): 8.

DTS-MA to DDP works fine.

I am using DEE 5.2.1 and ffmpeg 7.0 essentials

Command used:
`deew.exe -i input.mkv -ti 1 -o C:\_audio`
DDP profile is set to bluray 1536

After restoring DEEW 3.0.1 everything works fine again.

**Version**
3.2.1

**OS**
Windows 10

**Comment by pcroland** [comment]
Try to run it with `-k` and see if it generates the temp file as intended.
