### ISSUE TITLE
[IMPROVEMENT] Support 6.1 input.

### ISSUE THREAD

**Issue by bpoxy** [pcroland/deew#60]
Currently, 6.1 inputs are [disallowed](https://github.com/pcroland/deew/blob/aae7a2607ae44d265a0c17916aea08031dcd12e9/deew/__main__.py#L662). Is it possible to allow 6.1 and either upmix to 7.1 (by using Cb as Lb and Rb) or downmix to 5.1 (by mixing Cb into Ls and Rs)? Thanks.

**Comment by pcroland** [comment]
I don't plan to add support for any input channel layout that is not supported by DEE. If I were to support 6.1 then I would need to support other weird layouts aswell.

**Comment by bpoxy** [comment]
Fair enough. Thanks for the quick response.

**Comment by pcroland** [comment]
It would/could be difficult to detect the actual layout for non-standard layouts. And sometimes these inputs have empty channels aswell that would need to be detected aswell. And there are a lot more subjective decisions on what the default behaviour should be when someone encodes a file like this.
