### ISSUE TITLE
[QUESTION] 7.1 channel swapping.

### ISSUE THREAD

**Issue by bpoxy** [pcroland/deew#61]
Hoping you'd be willing to explain the rationale behind the [channel swapping logic](https://github.com/pcroland/deew/blob/aae7a2607ae44d265a0c17916aea08031dcd12e9/deew/__main__.py#L859), for my own understanding. Thank you.

**Comment by pcroland** [comment]
DEE assumes a wrong channel layout for w64 sources and swaps them, that's why deew also swaps it (so input and output has the same layout).

**Comment by pcroland** [comment]
https://github.com/pcroland/deew/blob/main/changelog.md#deew-127
