### ISSUE TITLE
dee requires sample rate 48 kHz , 96khz thd will fail

### ISSUE THREAD

**Issue by ted423** [pcroland/deew#7]
it's about "queen 2013"'s audio, it seems ffmpeg will create a near 20G wav and then deew will delete the wav and the xml.
could the py set output folder and not autodelete?

the before 7.1 ddp create sucessful 
maybe dee crashed?

**Comment by ted423** [comment]
it seems dee wrong
```
                          WARNING: pcm_to_ddp: Auto-enabling dolby_surround_ex_mode=yes in Blu-ray mode.
                          ERROR: pcm_to_ddp: Requires sample rate 48 kHz.
                          ERROR: framework: Audio filter stage (pcm_to_ddp) init failed. (Error code: 0)
                          ERROR: framework: Audio task failed.
                          ERROR: Workflow execution failed.
Time elapsed: 6.0835 seconds
Application exits with error code: 10
```

**Comment by ted423** [comment]
I had look Raging Fire 2021.
the ddp file made from mac ,the Sampling rate   is 48 khz, so ffmpeg need down sample?

**Comment by pcroland** [comment]
Try using `-k` so it keeps the temp files. After encoding files you can copy the dee command and run it with `--log-file log` so it gives you a full log.

**Comment by ted423** [comment]
> Try using `-k` so it keeps the temp files. After encoding files you can copy the dee command and run it with `--log-file log` so it gives you a full log.

sorry, miss that, and I change the issue title

**Comment by pcroland** [comment]
Closing this, you need to feed deew encodable sample rate, 96kHz can be used for TrueHD encodes though. I'll implement some mediainfo/ffmpeg info parsing for error handling and for the removal of the `-c` option all together sometimes.

**Comment by ted423** [comment]
I use useac3to resample to 48khz，but the dee done and the audio only 20min
the dmp show error too(but use 96khz wavs),but the audio is 2:25:01
![image](https://user-images.githubusercontent.com/7042766/154178587-1cdc4717-ca73-4c27-95f1-dedc24cbc665.png)

**Comment by pcroland** [comment]
for sample rate conversion use sox instead of abandonware eac3to:
`ffmpeg -drc_scale 0 -i input -v quiet -f sox - | sox -p -S -b 32 output rate 48000`

**Comment by ted423** [comment]
thx , I'll try

**Comment by ted423** [comment]
use sox

```
Format                      : Wave
File size                   : 12.4 GiB
Duration                    : 2 h 25 min
Overall bit rate mode       : Constant
Overall bit rate            : 12.3 Mb/s

Audio
Format                      : PCM
Format settings             : Little / Signed
Codec ID                    : 00000001-0000-0010-8000-00AA00389B71
Duration                    : 2 h 25 min
Bit rate mode               : Constant
Bit rate                    : 12.3 Mb/s
Channel(s)                  : 8 channels
Channel layout              : L R C LFE Lb Rb Ls Rs
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 12.4 GiB (100%)
```

the player only can play 5min and dee only make 5min ddp(useac3to resample is 20min)

and I had tried two remux.

the thd after ffmpeg trans to wav can play whole

**Comment by pcroland** [comment]
Try this:
`ffmpeg -y -drc_scale 0 -i input -c:a pcm_s24le -rf64 always out.wav`
Does ffmpeg give you any decoding warning/error?

**Comment by ted423** [comment]
Codec AVOption drc_scale (percentage of dynamic range compression to apply) specified for input file #0 (D:\Seed\Queen.2013.BluRay.REMUX.1080p.AVC.TrueHD.7.1-LHD\Queen.2013.BluRay.REMUX.1080p.AVC.TrueHD.7.1-LHD_track2_[hin]_DELAY 0ms.thd) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.

**Comment by pcroland** [comment]
Try without `-drc_scale 0` then.

**Comment by ted423** [comment]
ffmpeg  without -drc_scale 0 is no warning

try no  `-drc_scale 0` with sox is still same
sox WARN rate: rate clipped 26 samples; decrease volume?
Done.

**Comment by pcroland** [comment]
Send me the file on Telegram, I'll take a look tomorrow.

**Comment by ted423** [comment]
queen 2013's audio
you can try Queen.2013.1080p.BluRay.Remux.AVC.TrueHD.7.1-TEPES
or @pcroland on telegram?

**Comment by pcroland** [comment]
yes

**Comment by ValZapod** [comment]
FFmpeg thd decoder does not support applying DRC, so -drc_scale 0 does not make sense here. (After all that makes THD not lossless.) MFF microsoft and EAE.exe support applying DRC though.

**Comment by pcroland** [comment]
`-drc_scale 0` is applied to every ffmpeg command, if there's no DRC FFmpeg will ignore it.
